training:
  Lx: 60.0
  Ly: 30.0
  scale: 1
  problem_type: "cantilever_corner"

  num_iterations: 150
  lr: 0.001
  jitted_coords: false
  grad_clip_norm: 1.0
  max_consecutive_errors: 30
  train_rng_seed: 42
  model_rng_seed: 61
  helmholtz_radius: 0.0
  plateau:
    patience: 20
    cooldown: 0
    factor: 0.5
    rtol: 0.05
    accumulation_size: 1

models:
  - model_type: SIREN
    model_kwargs:
      num_channels_in: 2
      num_channels_out: 1
      num_layers: 4
      num_latent_channels: 64
      omega: 17.0
    training:
      target_density: 0.5
      penalty: 10

  - model_type: SIREN
    model_kwargs:
      num_channels_in: 2
      num_channels_out: 1
      num_layers: 4
      num_latent_channels: 64
      omega: 17.0
    training:
      target_density: 0.5
      penalty: 10

  - model_type: SIREN
    model_kwargs:
      num_channels_in: 2
      num_channels_out: 1
      num_layers: 4
      num_latent_channels: 64
      omega: 17.0
    training:
      target_density: 0.5
      penalty: 10

  - model_type: SIREN
    model_kwargs:
      num_channels_in: 2
      num_channels_out: 1
      num_layers: 4
      num_latent_channels: 64
      omega: 17.0
    training:
      target_density: 0.5
      penalty: 10

  - model_type: SIREN
    model_kwargs:
      num_channels_in: 2
      num_channels_out: 1
      num_layers: 4
      num_latent_channels: 64
      omega: 17.0
    training:
      target_density: 0.5
      penalty: 10

  - model_type: SIREN
    model_kwargs:
      num_channels_in: 2
      num_channels_out: 1
      num_layers: 4
      num_latent_channels: 64
      omega: 17.0
    training:
      target_density: 0.5
      penalty: 10

  - model_type: SIREN
    model_kwargs:
      num_channels_in: 2
      num_channels_out: 1
      num_layers: 4
      num_latent_channels: 64
      omega: 17.0
    training:
      target_density: 0.5
      penalty: 10

  - model_type: SIREN
    model_kwargs:
      num_channels_in: 2
      num_channels_out: 1
      num_layers: 4
      num_latent_channels: 64
      omega: 17.0
    training:
      target_density: 0.5
      penalty: 10