training:
  Lx: 60.0
  Ly: 30.0
  scale: 3
  dirichlet_boundary_conditions: "cantilever_left_support"

  num_iterations: 100
  lr: 0.001
  jitted_coords: false
  grad_clip_norm: 1.0
  max_consecutive_errors: 30
  train_rng_seed: 534
  model_rng_seed: 34
  deterministic_models: true
  helmholtz_radius: 0.0
  learning_rate_schedule:
    init_value: 1.0
    end_value: 0.05
    power: 2
    transition_steps: 60
    transition_begin: 40

models:
  - model_type: SIREN
    model_kwargs:
      num_channels_in: 2
      num_channels_out: 1
      num_layers: 3
      num_latent_channels: 512
      omega: 23.0
    training:
      target_density: 0.82
      penalty: 0.003
      neumann_boundary_conditions: "cantilever_corner"

  - model_type: SIREN
    model_kwargs:
      num_channels_in: 2
      num_channels_out: 1
      num_layers: 3
      num_latent_channels: 512
      omega: 23.0
    training:
      target_density: 0.68
      penalty: 0.003
      neumann_boundary_conditions: "cantilever_lower_mid"

  - model_type: SIREN
    model_kwargs:
      num_channels_in: 2
      num_channels_out: 1
      num_layers: 3
      num_latent_channels: 512
      omega: 23.0
    training:
      target_density: 0.58
      penalty: 0.003
      neumann_boundary_conditions: "cantilever_mid"

  - model_type: SIREN
    model_kwargs:
      num_channels_in: 2
      num_channels_out: 1
      num_layers: 3
      num_latent_channels: 512
      omega: 23.0
    training:
      target_density: 0.47
      penalty: 0.003
      neumann_boundary_conditions: "cantilever_upper_mid"

  - model_type: SIREN
    model_kwargs:
      num_channels_in: 2
      num_channels_out: 1
      num_layers: 3
      num_latent_channels: 512
      omega: 23.0
    training:
      target_density: 0.39
      penalty: 0.003
      neumann_boundary_conditions: "cantilever_top_corner"

  - model_type: SIREN
    model_kwargs:
      num_channels_in: 2
      num_channels_out: 1
      num_layers: 3
      num_latent_channels: 512
      omega: 23.0
    training:
      target_density: 0.31
      penalty: 0.003
      neumann_boundary_conditions: "cantilever_double"

  - model_type: SIREN
    model_kwargs:
      num_channels_in: 2
      num_channels_out: 1
      num_layers: 3
      num_latent_channels: 512
      omega: 23.0
    training:
      target_density: 0.24
      penalty: 0.003
      neumann_boundary_conditions: "cantilever_triple"

  - model_type: SIREN
    model_kwargs:
      num_channels_in: 2
      num_channels_out: 1
      num_layers: 3
      num_latent_channels: 512
      omega: 23.0
    training:
      target_density: 0.14
      penalty: 0.003
      neumann_boundary_conditions: "cantilever_endcaps"
